### ISSUE TITLE
Make uganda to be selected by default in the admin dashboard

### ISSUE THREAD

**Issue by KimeraMoses** [KimeraMoses/dav-safaris#4]
![image](https://github.com/KimeraMoses/dav-safaris/assets/55502046/24e0128a-74c3-4b69-a31f-0ea40575eede)

Make uganda to be the default of this select by county dropdown since all the countries displayed initially are for Uganda

_Originally posted by @KimeraMoses in https://github.com/KimeraMoses/dav-safaris/issues/1#issuecomment-1631943377_

**Comment by KimeraMoses** [comment]
It also seems like we are fetching all the countries and then filter when a country is selected, can you please only fetch tours for the selected country?

Meaning that initially, only tours within Uganda should be fetched and when one selects another country then we fetch those countries. We have no reason for fetching all countries here yet we only display tours of a single country at a time.

**Comment by ssemugenyi** [comment]
I have fixed this and am only fetching tours of the selected country

**Comment by ssemugenyi** [comment]
Changes will be available soon
